# Generated by Django 5.2.10 on 2026-01-25 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paginas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('imagen_url', models.URLField()),
                ('public_id', models.CharField(max_length=200)),
                ('creada', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
